services:
  coordinator:
    build: ./coordinator
    ports:
      - "8000:8000"
    depends_on:
      - face-analysis
      - disease-analysis
    networks:
      - health-net

  disease-analysis:
    build: ./disease-analysis
    networks:
      - health-net

  face-analysis:
    build: ./face-analysis
    networks:
      - health-net

networks:
  health-net:
    driver: bridge