spring.application.name=backend-api

server.port=8084

# Swagger UI settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/v3/api-docs

# Grouping multiple services in Swagger UI
springdoc.swagger-ui.urls[0].name=Orchestration Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[1].name=Authentication Service
springdoc.swagger-ui.urls[1].url=http://localhost:8080/v3/api-docs
springdoc.swagger-ui.urls[2].name=Chat Service
springdoc.swagger-ui.urls[2].url=http://localhost:8082/v3/api-docs
springdoc.swagger-ui.urls[3].name=User Service
springdoc.swagger-ui.urls[3].url=http://localhost:8081/v3/api-docs

jwt.secret=w7N1c4K1vR3f8Yz8L0pM6sH5bT2eQ0aX
jwt.expiration-ms=3600000
services.face-detection.url=http://localhost:8082/api/llm/analyze
services.llm-fastapi.url=http://localhost:8083/analyze
services.llm.spring.chat.url=http://localhost:8082/api/llm/chat
services.llm.spring.transcribe.url=http://localhost:8082/api/llm/transcribe
services.chat.creation.url=http://localhost:8082/api/users/{userId}/chats/create
services.chat.getter.url=http://localhost:8082/api/chats/{userId}/byId
services.chat.history.url=http://localhost:8082/api/chats/{chatId}/history/{id}